/* The following code was generated by JFlex 1.3.5 on 5/10/20, 3:23 PM */

package cup.pFinal;
import java_cup.runtime.ComplexSymbolFactory;
import java_cup.runtime.ComplexSymbolFactory.Location;
import java_cup.runtime.Symbol;
import java.lang.*;
import java.io.InputStreamReader;

/* Custom Imports */



/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.3.5
 * on 5/10/20, 3:23 PM from the specification file
 * <tt>file:/home/dumont_dev/work/ws/java/universidad/pl/PL_PFINAL/lexer.jflex</tt>
 */
public class Lexer implements sym, java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  final public static int YYEOF = -1;

  /** initial size of the lookahead buffer */
  final private static int YY_BUFFERSIZE = 16384;

  /** lexical states */
  final public static int CODESEG = 1;
  final public static int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  final private static String yycmap_packed = 
    "\11\0\1\35\1\2\1\0\1\35\1\1\22\0\1\35\1\7\1\0"+
    "\1\12\2\0\1\50\1\43\1\37\1\61\1\5\1\16\1\65\1\10"+
    "\1\13\1\4\1\3\11\14\1\66\1\60\1\6\1\62\1\11\2\0"+
    "\1\30\1\53\1\17\1\46\1\15\1\26\2\42\1\56\2\42\1\32"+
    "\1\57\1\45\1\51\2\42\1\23\1\34\1\22\1\24\2\42\1\21"+
    "\2\42\4\0\1\42\1\0\1\31\1\54\1\55\1\47\1\25\1\27"+
    "\1\41\1\42\1\56\2\42\1\33\1\57\1\45\1\40\1\36\1\42"+
    "\1\23\1\34\1\22\1\24\2\42\1\20\2\42\1\63\1\52\1\64"+
    "\u1f9b\0\1\44\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  final private static char [] yycmap = yy_unpack_cmap(yycmap_packed);

  /** 
   * Translates a state to a row index in the transition table
   */
  final private static int yy_rowMap [] = { 
        0,    55,   110,   165,   110,   220,   275,   110,   330,   110, 
      385,   110,   440,   495,   110,   550,   605,   660,   715,   770, 
      825,   880,   935,   990,   110,  1045,  1100,  1155,  1210,   110, 
      110,  1265,  1320,   110,   110,  1375,   110,   110,   110,  1430, 
     1485,  1540,  1595,  1650,  1705,  1760,  1815,   110,   110,  1870, 
     1925,  1980,  2035,  2090,  2145,  2200,  2255,  2310,  2365,  2420, 
     2475,  2530,  2585,   605,  2640,  2695,  2750,  2805,  2860,   110, 
      110,  1540,  1595,  2915,   110,  2970,  3025,  3080,  3135,  3190, 
     3245,  3300,  3355,  3410,  3465,  3520,  3575,   605,  3630,  3685, 
     3740,   110,   605,  3795,  3850,  3905,  3960,  4015,  4070,   605, 
     4125,   605,   110,  4180,  4235,  4290,   110,  4345,   605,  4400, 
     4455,  4510,  4565,  4620,  4675,  4730,  4785,   605,  4840,  4895, 
     4950,  5005,  5060,   605,  5115,  5170,   605,  5225,  5280,   605, 
     5335,  5390,  3905,  5445,  5500,   605,  5555,  5610,  5665,   605, 
      605,  5720,   605,   605,  5775,  5830,   605
  };

  /** 
   * The packed transition table of the DFA (part 0)
   */
  final private static String yy_packed0 = 
    "\1\3\1\4\1\5\1\6\1\7\1\10\1\11\1\3"+
    "\1\12\1\13\1\3\1\14\1\15\1\16\1\17\1\20"+
    "\2\21\1\22\1\23\1\21\1\24\2\25\2\26\1\21"+
    "\1\27\1\30\1\5\1\21\1\31\1\32\2\21\1\33"+
    "\1\34\1\35\2\21\1\36\1\32\1\37\2\40\1\20"+
    "\1\21\1\41\1\42\1\43\1\44\1\45\1\46\1\47"+
    "\1\50\67\3\71\0\1\5\67\0\1\51\7\0\1\52"+
    "\1\51\3\0\2\53\51\0\1\54\1\55\70\0\1\56"+
    "\2\0\1\57\47\0\1\60\66\0\1\61\7\0\1\51"+
    "\7\0\1\62\1\51\1\63\54\0\1\21\10\0\2\21"+
    "\1\0\16\21\1\0\1\21\1\0\3\21\2\0\1\64"+
    "\2\21\1\0\1\21\1\0\5\21\12\0\1\21\10\0"+
    "\2\21\1\0\11\21\2\65\3\21\1\0\1\21\1\0"+
    "\3\21\2\0\3\21\1\0\1\21\1\0\5\21\12\0"+
    "\1\21\10\0\2\21\1\0\16\21\1\0\1\21\1\0"+
    "\3\21\2\0\3\21\1\0\1\21\1\0\5\21\12\0"+
    "\1\21\10\0\2\21\1\0\4\21\1\66\11\21\1\0"+
    "\1\21\1\0\3\21\2\0\3\21\1\0\1\21\1\0"+
    "\5\21\12\0\1\21\10\0\1\21\1\67\1\0\6\21"+
    "\1\67\7\21\1\0\1\21\1\0\3\21\2\0\3\21"+
    "\1\0\1\21\1\0\5\21\12\0\1\21\10\0\2\21"+
    "\1\0\1\21\1\70\14\21\1\0\1\21\1\0\3\21"+
    "\2\0\1\64\2\21\1\0\1\21\1\0\5\21\12\0"+
    "\1\21\10\0\2\21\1\0\5\21\1\71\3\21\2\72"+
    "\3\21\1\0\1\21\1\0\3\21\2\0\3\21\1\0"+
    "\1\21\1\0\3\21\1\73\1\21\12\0\1\21\10\0"+
    "\2\21\1\0\16\21\1\0\1\21\1\0\3\21\2\0"+
    "\1\74\2\21\1\0\1\21\1\0\5\21\12\0\1\21"+
    "\10\0\2\21\1\0\16\21\1\0\1\21\1\0\1\75"+
    "\2\21\2\0\3\21\1\0\1\21\1\0\5\21\12\0"+
    "\1\21\10\0\2\21\1\0\3\21\1\76\12\21\1\0"+
    "\1\21\1\0\3\21\2\0\3\21\1\0\1\21\1\0"+
    "\3\21\1\77\1\21\12\0\1\21\10\0\2\21\1\0"+
    "\4\21\1\100\11\21\1\0\1\21\1\0\3\21\2\0"+
    "\3\21\1\0\1\21\1\0\5\21\7\0\2\101\1\0"+
    "\64\101\2\102\1\0\64\102\3\0\1\21\10\0\2\21"+
    "\1\0\16\21\1\0\1\21\1\0\1\103\2\21\2\0"+
    "\3\21\1\0\1\103\1\0\5\21\12\0\1\21\10\0"+
    "\2\21\1\0\16\21\1\0\1\21\1\0\1\104\2\21"+
    "\2\0\3\21\1\0\1\104\1\0\5\21\12\0\1\21"+
    "\10\0\2\21\1\0\16\21\1\0\1\21\1\0\3\21"+
    "\2\0\3\21\1\0\1\21\1\0\3\21\1\105\1\21"+
    "\71\0\1\106\66\0\1\107\7\0\1\51\7\0\1\52"+
    "\1\51\55\0\1\110\10\0\1\110\55\0\1\111\10\0"+
    "\2\111\1\0\1\111\6\0\1\111\1\0\1\111\15\0"+
    "\1\111\4\0\1\111\13\0\1\54\1\112\1\113\64\54"+
    "\5\55\1\114\61\55\10\0\1\115\56\0\2\57\1\0"+
    "\64\57\3\0\1\116\10\0\1\116\55\0\1\110\4\0"+
    "\1\52\3\0\1\110\1\0\1\52\53\0\1\21\10\0"+
    "\2\21\1\0\3\21\1\117\12\21\1\0\1\21\1\0"+
    "\3\21\2\0\3\21\1\0\1\21\1\0\5\21\12\0"+
    "\1\21\10\0\2\21\1\0\4\21\1\120\11\21\1\0"+
    "\1\21\1\0\3\21\2\0\3\21\1\0\1\21\1\0"+
    "\5\21\12\0\1\21\10\0\2\21\1\0\5\21\1\121"+
    "\10\21\1\0\1\21\1\0\3\21\2\0\3\21\1\0"+
    "\1\21\1\0\5\21\12\0\1\21\10\0\2\21\1\0"+
    "\3\21\1\122\5\21\2\123\3\21\1\0\1\21\1\0"+
    "\3\21\2\0\3\21\1\0\1\21\1\0\5\21\12\0"+
    "\1\21\10\0\2\21\1\0\16\21\1\0\1\124\1\0"+
    "\3\21\2\0\3\21\1\0\1\21\1\0\5\21\12\0"+
    "\1\21\10\0\2\21\1\0\16\21\1\0\1\21\1\0"+
    "\3\21\2\0\1\125\2\21\1\0\1\21\1\0\5\21"+
    "\12\0\1\21\10\0\2\21\1\0\13\21\2\126\1\21"+
    "\1\0\1\21\1\0\3\21\2\0\3\21\1\0\1\21"+
    "\1\0\5\21\12\0\1\21\10\0\2\21\1\0\16\21"+
    "\1\0\1\21\1\0\3\21\2\0\1\127\2\21\1\0"+
    "\1\21\1\0\5\21\12\0\1\21\10\0\2\21\1\0"+
    "\16\21\1\0\1\21\1\0\3\21\2\0\1\21\2\130"+
    "\1\0\1\21\1\0\5\21\12\0\1\21\10\0\2\21"+
    "\1\0\16\21\1\0\1\21\1\0\1\21\1\131\1\21"+
    "\2\0\3\21\1\0\1\21\1\0\5\21\12\0\1\21"+
    "\10\0\2\21\1\0\4\21\1\132\11\21\1\0\1\21"+
    "\1\0\3\21\2\0\3\21\1\0\1\21\1\0\5\21"+
    "\12\0\1\21\10\0\2\21\1\0\16\21\1\0\1\21"+
    "\1\0\3\21\2\0\1\133\2\21\1\0\1\21\1\0"+
    "\5\21\52\0\1\134\67\0\1\134\25\0\1\21\10\0"+
    "\2\21\1\0\3\21\1\135\12\21\1\0\1\21\1\0"+
    "\3\21\2\0\3\21\1\0\1\21\1\0\5\21\12\0"+
    "\1\21\10\0\2\21\1\0\16\21\1\0\1\21\1\0"+
    "\1\136\2\21\2\0\3\21\1\0\1\136\1\0\5\21"+
    "\12\0\1\21\10\0\1\21\1\137\1\0\6\21\1\137"+
    "\7\21\1\0\1\21\1\0\3\21\2\0\3\21\1\0"+
    "\1\21\1\0\5\21\11\0\1\113\64\0\4\55\1\113"+
    "\1\114\61\55\10\0\1\140\61\0\1\116\10\0\1\116"+
    "\1\63\54\0\1\21\10\0\1\21\1\141\1\0\6\21"+
    "\1\141\7\21\1\0\1\21\1\0\1\142\2\21\2\0"+
    "\3\21\1\0\1\142\1\0\5\21\12\0\1\21\10\0"+
    "\2\21\1\0\11\21\2\143\3\21\1\0\1\21\1\0"+
    "\3\21\2\0\3\21\1\0\1\21\1\0\5\21\12\0"+
    "\1\21\10\0\1\21\1\144\1\0\6\21\1\144\7\21"+
    "\1\0\1\21\1\0\3\21\2\0\3\21\1\0\1\21"+
    "\1\0\5\21\12\0\1\21\10\0\2\21\1\0\5\21"+
    "\1\145\10\21\1\0\1\21\1\0\3\21\2\0\3\21"+
    "\1\0\1\21\1\0\5\21\12\0\1\21\10\0\2\21"+
    "\1\0\13\21\2\146\1\21\1\0\1\21\1\0\3\21"+
    "\2\0\3\21\1\0\1\21\1\0\5\21\12\0\1\21"+
    "\10\0\2\21\1\0\16\21\1\0\1\21\1\147\3\21"+
    "\2\0\3\21\1\0\1\21\1\0\5\21\12\0\1\21"+
    "\10\0\2\21\1\0\1\150\15\21\1\0\1\21\1\0"+
    "\3\21\2\0\3\21\1\0\1\21\1\0\2\21\1\150"+
    "\2\21\12\0\1\21\10\0\2\21\1\0\15\21\1\121"+
    "\1\0\1\21\1\0\3\21\2\0\3\21\1\0\1\21"+
    "\1\0\5\21\12\0\1\21\10\0\2\21\1\0\15\21"+
    "\1\151\1\0\1\21\1\0\3\21\2\0\3\21\1\0"+
    "\1\21\1\0\4\21\1\152\12\0\1\21\10\0\2\21"+
    "\1\0\16\21\1\0\1\21\1\153\3\21\2\0\3\21"+
    "\1\0\1\21\1\0\5\21\12\0\1\21\10\0\2\21"+
    "\1\0\5\21\1\154\10\21\1\0\1\21\1\0\3\21"+
    "\2\0\3\21\1\0\1\21\1\0\5\21\12\0\1\21"+
    "\10\0\2\21\1\0\16\21\1\0\1\21\1\0\1\155"+
    "\2\21\2\0\3\21\1\0\1\155\1\0\5\21\12\0"+
    "\1\21\10\0\2\21\1\0\13\21\2\156\1\21\1\0"+
    "\1\21\1\0\3\21\2\0\3\21\1\0\1\21\1\0"+
    "\5\21\12\0\1\21\10\0\2\21\1\0\16\21\1\0"+
    "\1\21\1\0\3\21\2\0\1\157\2\21\1\0\1\21"+
    "\1\0\5\21\7\0\10\140\1\160\56\140\3\0\1\21"+
    "\10\0\2\21\1\0\4\21\1\161\11\21\1\0\1\21"+
    "\1\0\3\21\2\0\3\21\1\0\1\21\1\0\5\21"+
    "\12\0\1\21\10\0\2\21\1\0\16\21\1\0\1\21"+
    "\1\0\3\21\2\0\1\162\2\21\1\0\1\21\1\0"+
    "\5\21\12\0\1\21\10\0\2\21\1\0\1\163\15\21"+
    "\1\0\1\21\1\0\3\21\2\0\3\21\1\0\1\21"+
    "\1\0\2\21\1\163\2\21\12\0\1\21\10\0\2\21"+
    "\1\0\4\21\1\164\11\21\1\0\1\21\1\0\3\21"+
    "\2\0\3\21\1\0\1\21\1\0\5\21\12\0\1\21"+
    "\10\0\2\21\1\0\16\21\1\0\1\21\1\0\3\21"+
    "\2\0\3\21\1\0\1\21\1\0\3\21\1\165\1\21"+
    "\12\0\1\21\10\0\2\21\1\0\16\21\1\0\1\21"+
    "\1\0\3\21\2\0\3\21\1\0\1\21\1\0\3\21"+
    "\1\166\1\21\12\0\1\21\10\0\2\21\1\0\16\21"+
    "\1\0\1\21\1\0\3\21\2\0\3\21\1\0\1\21"+
    "\1\0\3\21\1\167\1\21\12\0\1\21\10\0\2\21"+
    "\1\0\1\170\15\21\1\0\1\21\1\0\3\21\2\0"+
    "\3\21\1\0\1\21\1\0\2\21\1\170\2\21\12\0"+
    "\1\21\10\0\1\21\1\171\1\0\6\21\1\171\7\21"+
    "\1\0\1\21\1\0\3\21\2\0\3\21\1\0\1\21"+
    "\1\0\5\21\12\0\1\21\10\0\2\21\1\0\3\21"+
    "\1\172\12\21\1\0\1\21\1\0\3\21\2\0\3\21"+
    "\1\0\1\21\1\0\5\21\7\0\10\140\1\173\56\140"+
    "\3\0\1\21\10\0\2\21\1\0\16\21\1\0\1\21"+
    "\1\0\1\174\2\21\2\0\3\21\1\0\1\174\1\0"+
    "\5\21\12\0\1\21\10\0\2\21\1\0\1\175\15\21"+
    "\1\0\1\21\1\0\3\21\2\0\3\21\1\0\1\21"+
    "\1\0\2\21\1\175\2\21\12\0\1\21\10\0\2\21"+
    "\1\0\3\21\1\176\12\21\1\0\1\21\1\0\3\21"+
    "\2\0\3\21\1\0\1\21\1\0\5\21\12\0\1\21"+
    "\10\0\2\21\1\0\16\21\1\0\1\21\1\0\3\21"+
    "\2\0\1\177\2\21\1\0\1\21\1\0\5\21\12\0"+
    "\1\21\10\0\2\21\1\0\16\21\1\0\1\21\1\0"+
    "\1\200\2\21\2\0\3\21\1\0\1\200\1\0\5\21"+
    "\12\0\1\21\10\0\1\21\1\201\1\0\6\21\1\201"+
    "\7\21\1\0\1\21\1\0\3\21\2\0\3\21\1\0"+
    "\1\21\1\0\5\21\12\0\1\21\10\0\2\21\1\0"+
    "\3\21\1\202\12\21\1\0\1\21\1\0\3\21\2\0"+
    "\3\21\1\0\1\21\1\0\5\21\12\0\1\21\10\0"+
    "\2\21\1\0\11\21\2\203\3\21\1\0\1\21\1\0"+
    "\3\21\2\0\3\21\1\0\1\21\1\0\5\21\12\0"+
    "\1\21\10\0\2\21\1\0\4\21\1\204\11\21\1\0"+
    "\1\21\1\0\3\21\2\0\3\21\1\0\1\21\1\0"+
    "\5\21\7\0\10\140\1\173\1\205\55\140\3\0\1\21"+
    "\10\0\1\21\1\206\1\0\6\21\1\206\7\21\1\0"+
    "\1\21\1\0\3\21\2\0\3\21\1\0\1\21\1\0"+
    "\5\21\12\0\1\21\10\0\1\21\1\207\1\0\6\21"+
    "\1\207\7\21\1\0\1\21\1\0\3\21\2\0\3\21"+
    "\1\0\1\21\1\0\5\21\12\0\1\21\10\0\2\21"+
    "\1\0\16\21\1\0\1\21\1\0\3\21\2\0\1\210"+
    "\2\21\1\0\1\21\1\0\5\21\12\0\1\21\10\0"+
    "\2\21\1\0\16\21\1\0\1\21\1\0\3\21\2\0"+
    "\1\211\2\21\1\0\1\21\1\0\5\21\12\0\1\21"+
    "\10\0\2\21\1\0\16\21\1\0\1\21\1\0\3\21"+
    "\2\0\1\212\2\21\1\0\1\21\1\0\5\21\12\0"+
    "\1\21\10\0\2\21\1\0\11\21\2\213\3\21\1\0"+
    "\1\21\1\0\3\21\2\0\3\21\1\0\1\21\1\0"+
    "\5\21\12\0\1\21\10\0\2\21\1\0\15\21\1\214"+
    "\1\0\1\21\1\0\3\21\2\0\3\21\1\0\1\21"+
    "\1\0\5\21\12\0\1\21\10\0\2\21\1\0\4\21"+
    "\1\215\11\21\1\0\1\21\1\0\3\21\2\0\3\21"+
    "\1\0\1\21\1\0\5\21\12\0\1\21\10\0\2\21"+
    "\1\0\3\21\1\216\12\21\1\0\1\21\1\0\3\21"+
    "\2\0\3\21\1\0\1\21\1\0\5\21\12\0\1\21"+
    "\10\0\2\21\1\0\16\21\1\0\1\21\1\0\1\217"+
    "\2\21\2\0\3\21\1\0\1\217\1\0\5\21\12\0"+
    "\1\21\10\0\2\21\1\0\15\21\1\220\1\0\1\21"+
    "\1\0\3\21\2\0\3\21\1\0\1\21\1\0\5\21"+
    "\12\0\1\21\10\0\2\21\1\0\4\21\1\221\11\21"+
    "\1\0\1\21\1\0\3\21\2\0\3\21\1\0\1\21"+
    "\1\0\5\21\12\0\1\21\10\0\2\21\1\0\11\21"+
    "\2\222\3\21\1\0\1\21\1\0\3\21\2\0\3\21"+
    "\1\0\1\21\1\0\5\21\12\0\1\21\10\0\2\21"+
    "\1\0\15\21\1\223\1\0\1\21\1\0\3\21\2\0"+
    "\3\21\1\0\1\21\1\0\5\21\7\0";

  /** 
   * The transition table of the DFA
   */
  final private static int yytrans [] = yy_unpack();


  /* error codes */
  final private static int YY_UNKNOWN_ERROR = 0;
  final private static int YY_ILLEGAL_STATE = 1;
  final private static int YY_NO_MATCH = 2;
  final private static int YY_PUSHBACK_2BIG = 3;

  /* error messages for the codes above */
  final private static String YY_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Internal error: unknown state",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * YY_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private final static byte YY_ATTRIBUTE[] = {
     0,  0,  9,  1,  9,  1,  1,  9,  1,  9,  1,  9,  1,  1,  9,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  9,  1,  1,  1,  1,  9,  9,  1, 
     1,  9,  9,  1,  9,  9,  9,  1,  1,  0,  0,  0,  0,  0,  1,  9, 
     9,  0,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     0,  0,  1,  1,  1,  9,  9,  1,  1,  1,  9,  0,  0,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  9,  1,  1,  1,  0, 
     1,  1,  1,  1,  1,  1,  9,  1,  1,  1,  9,  1,  1,  1,  1,  0, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  0,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1
  };

  /** the input device */
  private java.io.Reader yy_reader;

  /** the current state of the DFA */
  private int yy_state;

  /** the current lexical state */
  private int yy_lexical_state = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char yy_buffer[] = new char[YY_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int yy_markedPos;

  /** the textposition at the last state to be included in yytext */
  private int yy_pushbackPos;

  /** the current text position in the buffer */
  private int yy_currentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int yy_startRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int yy_endRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn; 

  /** 
   * yy_atBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean yy_atBOL = true;

  /** yy_atEOF == true <=> the scanner is at the EOF */
  private boolean yy_atEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean yy_eof_done;

  /* user code: */
	

    public Lexer(ComplexSymbolFactory sf, java.io.InputStream is){
		this(is);
        symbolFactory = sf;
    }
	public Lexer(ComplexSymbolFactory sf, java.io.Reader reader){
		this(reader);
        symbolFactory = sf;
    }
    
    private StringBuffer sb;
    private ComplexSymbolFactory symbolFactory;
    private int csline,cscolumn;

    public Symbol symbol(String name, int code){
		return symbolFactory.newSymbol(name, code,
						new Location(yyline+1,yycolumn+1, yychar), // -yylength()
						new Location(yyline+1,yycolumn+yylength(), yychar+yylength())
				);
    }
    public Symbol symbol(String name, int code, String lexem){
	return symbolFactory.newSymbol(name, code, 
						new Location(yyline+1, yycolumn +1, yychar), 
						new Location(yyline+1,yycolumn+yylength(), yychar+yylength()), lexem);
    }
    
    protected void emit_warning(String message){
    	System.out.println("scanner warning: " + message + " at : 2 "+ 
    			(yyline+1) + " " + (yycolumn+1) + " " + yychar);
    }
    
    protected void emit_error(String message){
    	System.out.println("scanner error: " + message + " at : 2" + 
    			(yyline+1) + " " + (yycolumn+1) + " " + yychar);
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.yy_reader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the split, compressed DFA transition table.
   *
   * @return the unpacked transition table
   */
  private static int [] yy_unpack() {
    int [] trans = new int[5885];
    int offset = 0;
    offset = yy_unpack(yy_packed0, offset, trans);
    return trans;
  }

  /** 
   * Unpacks the compressed DFA transition table.
   *
   * @param packed   the packed transition table
   * @return         the index of the last entry
   */
  private static int yy_unpack(String packed, int offset, int [] trans) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do trans[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] yy_unpack_cmap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 166) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   IOException  if any I/O-Error occurs
   */
  private boolean yy_refill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (yy_startRead > 0) {
      System.arraycopy(yy_buffer, yy_startRead, 
                       yy_buffer, 0, 
                       yy_endRead-yy_startRead);

      /* translate stored positions */
      yy_endRead-= yy_startRead;
      yy_currentPos-= yy_startRead;
      yy_markedPos-= yy_startRead;
      yy_pushbackPos-= yy_startRead;
      yy_startRead = 0;
    }

    /* is the buffer big enough? */
    if (yy_currentPos >= yy_buffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[yy_currentPos*2];
      System.arraycopy(yy_buffer, 0, newBuffer, 0, yy_buffer.length);
      yy_buffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = yy_reader.read(yy_buffer, yy_endRead, 
                                            yy_buffer.length-yy_endRead);

    if (numRead < 0) {
      return true;
    }
    else {
      yy_endRead+= numRead;  
      return false;
    }
  }


  /**
   * Closes the input stream.
   */
  final public void yyclose() throws java.io.IOException {
    yy_atEOF = true;            /* indicate end of file */
    yy_endRead = yy_startRead;  /* invalidate buffer    */

    if (yy_reader != null)
      yy_reader.close();
  }


  /**
   * Closes the current stream, and resets the
   * scanner to read from a new input stream.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>YY_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  final public void yyreset(java.io.Reader reader) throws java.io.IOException {
    yyclose();
    yy_reader = reader;
    yy_atBOL  = true;
    yy_atEOF  = false;
    yy_endRead = yy_startRead = 0;
    yy_currentPos = yy_markedPos = yy_pushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    yy_lexical_state = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  final public int yystate() {
    return yy_lexical_state;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  final public void yybegin(int newState) {
    yy_lexical_state = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  final public String yytext() {
    return new String( yy_buffer, yy_startRead, yy_markedPos-yy_startRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  final public char yycharat(int pos) {
    return yy_buffer[yy_startRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  final public int yylength() {
    return yy_markedPos-yy_startRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void yy_ScanError(int errorCode) {
    String message;
    try {
      message = YY_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = YY_ERROR_MSG[YY_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  private void yypushback(int number)  {
    if ( number > yylength() )
      yy_ScanError(YY_PUSHBACK_2BIG);

    yy_markedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void yy_do_eof() throws java.io.IOException {
    if (!yy_eof_done) {
      yy_eof_done = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int yy_input;
    int yy_action;

    // cached fields:
    int yy_currentPos_l;
    int yy_startRead_l;
    int yy_markedPos_l;
    int yy_endRead_l = yy_endRead;
    char [] yy_buffer_l = yy_buffer;
    char [] yycmap_l = yycmap;

    int [] yytrans_l = yytrans;
    int [] yy_rowMap_l = yy_rowMap;
    byte [] yy_attr_l = YY_ATTRIBUTE;

    while (true) {
      yy_markedPos_l = yy_markedPos;

      yychar+= yy_markedPos_l-yy_startRead;

      boolean yy_r = false;
      for (yy_currentPos_l = yy_startRead; yy_currentPos_l < yy_markedPos_l;
                                                             yy_currentPos_l++) {
        switch (yy_buffer_l[yy_currentPos_l]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          yy_r = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          yy_r = true;
          break;
        case '\n':
          if (yy_r)
            yy_r = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          yy_r = false;
          yycolumn++;
        }
      }

      if (yy_r) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean yy_peek;
        if (yy_markedPos_l < yy_endRead_l)
          yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        else if (yy_atEOF)
          yy_peek = false;
        else {
          boolean eof = yy_refill();
          yy_markedPos_l = yy_markedPos;
          yy_buffer_l = yy_buffer;
          if (eof) 
            yy_peek = false;
          else 
            yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        }
        if (yy_peek) yyline--;
      }
      yy_action = -1;

      yy_startRead_l = yy_currentPos_l = yy_currentPos = 
                       yy_startRead = yy_markedPos_l;

      yy_state = yy_lexical_state;


      yy_forAction: {
        while (true) {

          if (yy_currentPos_l < yy_endRead_l)
            yy_input = yy_buffer_l[yy_currentPos_l++];
          else if (yy_atEOF) {
            yy_input = YYEOF;
            break yy_forAction;
          }
          else {
            // store back cached positions
            yy_currentPos  = yy_currentPos_l;
            yy_markedPos   = yy_markedPos_l;
            boolean eof = yy_refill();
            // get translated positions and possibly new buffer
            yy_currentPos_l  = yy_currentPos;
            yy_markedPos_l   = yy_markedPos;
            yy_buffer_l      = yy_buffer;
            yy_endRead_l     = yy_endRead;
            if (eof) {
              yy_input = YYEOF;
              break yy_forAction;
            }
            else {
              yy_input = yy_buffer_l[yy_currentPos_l++];
            }
          }
          int yy_next = yytrans_l[ yy_rowMap_l[yy_state] + yycmap_l[yy_input] ];
          if (yy_next == -1) break yy_forAction;
          yy_state = yy_next;

          int yy_attributes = yy_attr_l[yy_state];
          if ( (yy_attributes & 1) == 1 ) {
            yy_action = yy_state; 
            yy_markedPos_l = yy_currentPos_l; 
            if ( (yy_attributes & 8) == 8 ) break yy_forAction;
          }

        }
      }

      // store back cached position
      yy_markedPos = yy_markedPos_l;

      switch (yy_action) {

        case 30: 
        case 63: 
          {  return symbolFactory.newSymbol("OR", OR);  }
        case 148: break;
        case 62: 
          {  return symbolFactory.newSymbol("SI", SI);  }
        case 149: break;
        case 71: 
        case 77: 
          {  return symbolFactory.newSymbol("DOUBLENUMBER", DOUBLENUMBER, Double.parseDouble(yytext()));  }
        case 150: break;
        case 46: 
        case 73: 
        case 74: 
        case 132: 
          {  return symbolFactory.newSymbol("COMMENT", COMMENT, yytext());  }
        case 151: break;
        case 70: 
          {  return symbolFactory.newSymbol("ASSIGNSYMBOL", ASSIGNSYMBOL);  }
        case 152: break;
        case 5: 
        case 12: 
        case 40: 
          {  return symbolFactory.newSymbol("NUMBER", NUMBER, Integer.parseInt(yytext()));  }
        case 153: break;
        case 3: 
        case 4: 
          {                                }
        case 154: break;
        case 135: 
          {  return symbolFactory.newSymbol("FUNCION", FUNCION);  }
        case 155: break;
        case 123: 
          {  return symbolFactory.newSymbol("INTTYPE", INTTYPE);  }
        case 156: break;
        case 13: 
        case 15: 
        case 16: 
        case 17: 
        case 18: 
        case 19: 
        case 20: 
        case 21: 
        case 22: 
        case 23: 
        case 25: 
        case 28: 
        case 31: 
        case 32: 
        case 51: 
        case 52: 
        case 53: 
        case 54: 
        case 55: 
        case 56: 
        case 57: 
        case 58: 
        case 59: 
        case 60: 
        case 61: 
        case 66: 
        case 67: 
        case 68: 
        case 78: 
        case 79: 
        case 80: 
        case 81: 
        case 82: 
        case 83: 
        case 84: 
        case 85: 
        case 86: 
        case 88: 
        case 89: 
        case 90: 
        case 93: 
        case 94: 
        case 96: 
        case 97: 
        case 98: 
        case 100: 
        case 103: 
        case 104: 
        case 105: 
        case 107: 
        case 109: 
        case 110: 
        case 112: 
        case 113: 
        case 114: 
        case 115: 
        case 116: 
        case 118: 
        case 119: 
        case 120: 
        case 121: 
        case 124: 
        case 125: 
        case 127: 
        case 128: 
        case 130: 
        case 131: 
        case 133: 
        case 134: 
        case 136: 
        case 137: 
        case 138: 
        case 141: 
        case 144: 
        case 145: 
          {  return symbolFactory.newSymbol("ID", ID, yytext());  }
        case 157: break;
        case 69: 
          {  return symbolFactory.newSymbol("EQUALTO", EQUALTO);  }
        case 158: break;
        case 7: 
          {  return symbolFactory.newSymbol("TIMES", TIMES);  }
        case 159: break;
        case 8: 
          {  return symbolFactory.newSymbol("LTHAN", LTHAN);  }
        case 160: break;
        case 9: 
          {  return symbolFactory.newSymbol("MINUS", MINUS);  }
        case 161: break;
        case 10: 
          {  return symbolFactory.newSymbol("GTHAN", GTHAN);  }
        case 162: break;
        case 38: 
          {  return symbolFactory.newSymbol("COMMA", COMMA);  }
        case 163: break;
        case 117: 
          {  return symbolFactory.newSymbol("FINSI", FINSI);  }
        case 164: break;
        case 2: 
        case 26: 
        case 27: 
        case 35: 
        case 39: 
          {  emit_warning("Unrecognized character '" +yytext()+"' -- ignored");  }
        case 165: break;
        case 129: 
          {  return symbolFactory.newSymbol("STRUCTTYPE", STRUCTTYPE);  }
        case 166: break;
        case 29: 
        case 87: 
          {  return symbolFactory.newSymbol("AND", AND);  }
        case 167: break;
        case 11: 
          {  return symbolFactory.newSymbol("DOT", DOT);  }
        case 168: break;
        case 92: 
          {  return symbolFactory.newSymbol("NOT", NOT);  }
        case 169: break;
        case 143: 
          {  return symbolFactory.newSymbol("MIENTRAS", MIENTRAS);  }
        case 170: break;
        case 140: 
          {  return symbolFactory.newSymbol("CHARTYPE", CHARTYPE);  }
        case 171: break;
        case 139: 
          {  return symbolFactory.newSymbol("ENTONCES", ENTONCES);  }
        case 172: break;
        case 101: 
          {  return symbolFactory.newSymbol("REALTYPE", REALTYPE);  }
        case 173: break;
        case 146: 
          {  return symbolFactory.newSymbol("FINMIENTRAS", FINMIENTRAS);  }
        case 174: break;
        case 142: 
          {  return symbolFactory.newSymbol("BOOLEANTYPE", BOOLEANTYPE);  }
        case 175: break;
        case 72: 
          {  return symbolFactory.newSymbol("HEXNUMBER", HEXNUMBER, Integer.parseInt(yytext().substring(2,yytext().length()), 16));  }
        case 176: break;
        case 33: 
          {  return symbolFactory.newSymbol("SEMI", SEMI);  }
        case 177: break;
        case 14: 
          {  return symbolFactory.newSymbol("PLUS", PLUS);  }
        case 178: break;
        case 108: 
          {  return symbolFactory.newSymbol("SINO", SINO);  }
        case 179: break;
        case 6: 
          {  return symbolFactory.newSymbol("DIVIDEDBY", DIVIDEDBY);  }
        case 180: break;
        case 126: 
          {  return symbolFactory.newSymbol("RETURN", RETURN);  }
        case 181: break;
        case 36: 
          {  return symbolFactory.newSymbol("LBRACE", LBRACE);  }
        case 182: break;
        case 34: 
          {  return symbolFactory.newSymbol("RPAREN", RPAREN);  }
        case 183: break;
        case 24: 
          {  return symbolFactory.newSymbol("LPAREN", LPAREN);  }
        case 184: break;
        case 37: 
          {  return symbolFactory.newSymbol("RBRACE", RBRACE);  }
        case 185: break;
        case 47: 
          {  return symbolFactory.newSymbol("LEQUAL", LEQUAL);  }
        case 186: break;
        case 48: 
          {  return symbolFactory.newSymbol("GEQUAL", GEQUAL);  }
        case 187: break;
        case 102: 
          {  return symbolFactory.newSymbol("EXPONENTIAL", EXPONENTIAL, yytext());  }
        case 188: break;
        case 99: 
          {  return symbolFactory.newSymbol("BOOLEANVALUE", BOOLEANVALUE, yytext());  }
        case 189: break;
        case 106: 
          {  return symbolFactory.newSymbol("LOGARITHM", LOGARITHM, yytext());  }
        case 190: break;
        case 91: 
          {  return symbolFactory.newSymbol("CHARACTER", CHARACTER, yytext());  }
        case 191: break;
        default: 
          if (yy_input == YYEOF && yy_startRead == yy_currentPos) {
            yy_atEOF = true;
            yy_do_eof();
              {     return symbolFactory.newSymbol("EOF",sym.EOF);
 }
          } 
          else {
            yy_ScanError(YY_NO_MATCH);
          }
      }
    }
  }


}
