
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package cup.pFinal;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int COMMENT = 36;
  public static final int GEQUAL = 14;
  public static final int SI = 27;
  public static final int FUNCION = 33;
  public static final int LPAREN = 7;
  public static final int SEMI = 2;
  public static final int ENTONCES = 28;
  public static final int ASSIGNSYMBOL = 26;
  public static final int MINUS = 4;
  public static final int CHARACTER = 40;
  public static final int RPAREN = 8;
  public static final int NOT = 11;
  public static final int AND = 9;
  public static final int LTHAN = 15;
  public static final int FINMIENTRAS = 32;
  public static final int SINO = 29;
  public static final int EQUALTO = 12;
  public static final int OR = 10;
  public static final int MIENTRAS = 31;
  public static final int COMMA = 25;
  public static final int PLUS = 3;
  public static final int ID = 39;
  public static final int DOT = 24;
  public static final int EOF = 0;
  public static final int RETURN = 34;
  public static final int BOOLEANVALUE = 41;
  public static final int error = 1;
  public static final int BOOLEANTYPE = 19;
  public static final int DOUBLENUMBER = 37;
  public static final int NUMBER = 35;
  public static final int STRUCTTYPE = 20;
  public static final int REALTYPE = 18;
  public static final int TIMES = 5;
  public static final int GTHAN = 16;
  public static final int LBRACE = 22;
  public static final int LEQUAL = 13;
  public static final int INTTYPE = 17;
  public static final int RBRACE = 23;
  public static final int HEXNUMBER = 38;
  public static final int CHARTYPE = 21;
  public static final int FINSI = 30;
  public static final int DIVIDEDBY = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDEDBY",
  "LPAREN",
  "RPAREN",
  "AND",
  "OR",
  "NOT",
  "EQUALTO",
  "LEQUAL",
  "GEQUAL",
  "LTHAN",
  "GTHAN",
  "INTTYPE",
  "REALTYPE",
  "BOOLEANTYPE",
  "STRUCTTYPE",
  "CHARTYPE",
  "LBRACE",
  "RBRACE",
  "DOT",
  "COMMA",
  "ASSIGNSYMBOL",
  "SI",
  "ENTONCES",
  "SINO",
  "FINSI",
  "MIENTRAS",
  "FINMIENTRAS",
  "FUNCION",
  "RETURN",
  "NUMBER",
  "COMMENT",
  "DOUBLENUMBER",
  "HEXNUMBER",
  "ID",
  "CHARACTER",
  "BOOLEANVALUE"
  };
}

